// always use a random websocket generated by UUID
import uuid from "uuid/v4";

// PRODUCTION ASYNC
export const WebSocketURL =
  "wss://open.senrigan.io/ws/async/writeup/gpt2_medium/session/" + uuid() + "/";

// PRODUCTION DUMMY SOCKET
//export const WebSocketURL =
//  "wss://open.senrigan.io/ws/test/writeup/gpt2_medium/session/writeup/";

// LOCAL DEVELOPER ASYNC
//export const WebSocketURL =
//  "ws://127.0.0.1:8008/ws/async/writeup/gpt2_medium/session/" + uuid() + "/";

// LOCAL DEVELOPER DUMMY ASYNC
//export const WebSocketURL =
//  "ws://127.0.0.1:8008/ws/test/writeup/gpt2_medium/session/" + uuid() + "/";
