// always use a random websocket generated by UUID
import uuid from "uuid/v4";

export const GPT2_SMALL_MODEL_NAME = "gpt2";
export const GPT2_SMALL_LEGAL_MODEL_NAME = "gpt2-small-legal";
export const GPT2_MEDIUM_MODEL_NAME = "gpt2-medium";
export const GPT2_LARGE_MODEL_NAME = "gpt2-large";

export const XLNET_BASE_CASED_MODEL_NAME = "xlnet-base-cased";
export const XLNET_LARGE_CASED_MODEL_NAME = "xlnet-large-cased";

// PRODUCTION ASYNC
export const WebSocketURL =
  "wss://open.senrigan.io/ws/async/writeup/text_generation/session/" +
  uuid() +
  "/";

//PRODUCTION DUMMY SOCKET
//export const WebSocketURL =
//  "wss://open.senrigan.io/ws/test/writeup/text_generation/session/writeup/";

//const uuid_test = "uuid-test"

// LOCAL DEVELOPER ASYNC
//export const WebSocketURL =
//  "ws://127.0.0.1:5000/ws/async/writeup/text_generation/session/" + uuid() + "/";

// LOCAL DEVELOPER ASYNC CADDY
//export const WebSocketURL =
//  "ws://127.0.0.1/ws/async/writeup/text_generation/session/" + uuid() + "/";

// LOCAL DEVELOPER DUMMY ASYNC
//export const WebSocketURL =
//  "ws://127.0.0.1:8008/ws/test/writeup/text_generation/session/" + uuid() + "/";

// these are cached for two-three days to have a much faster loading time for the user
export const PROMPTS_TO_USE = [
  "The software innovations in the 20th century ",
  "Climate change has ",
  "The breakthrough in ",
  "Cancer research has revolutionized ",
  "Recent developments in ",
  "BANG! The earthquake shattered ",
  "We know now that ",
  "Nikola Tesla's inventions have ",
  "SpaceX's recent landing ",
  "I had my first ",
  "The pain radiated from my ",
  "The recent ",
  "South Korea ends ", // taken from a recent news article headline, not intended to build a dystopia headline
  "With recent funding from "
  // Prompts I Tried That Didn't Make The Cut ...
  //
  // "We must take action! " - just repeats itself
  // "Boy Name + Girl Name " - hilariously bad, makes a lot of non PC remarks
];

export const LEGAL_PROMPTS_TO_USE = [
  "The defendant has claimed ",
  "This court is here to ",
  "The jury has decided "
];

// use this as a way to back slatejs back to focus on where to add the comment
export const SPECIAL_CHARACTERS = [",", "!", ".", '"', "-", "'"];
