// always use a random websocket generated by UUID
import uuid from "uuid/v4";

export const WebSocketURL =
  "wss://open.senrigan.io/ws/writeup/gpt2_medium/session/" + uuid() + "/";

// this is a dummy test websocket
//export const WebSocketURL =
//  "wss://open.senrigan.io/ws/test/writeup/gpt2_medium/session/writeup/";
